version: '3'
services:
  angular-app:
    build:
      context: ./angular-app
    container_name: angular-app
    ports:
      - "4200:80"
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    networks:
      - app-network
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_OPTIONS_EDITORTHEME: default
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
      WAIT_HOSTS: mongodb:27017
      WAIT_RETRIES: 20
      WAIT_DELAY: 5
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
